### ISSUE TITLE
XtremePlayzCODE to the rescue!

### ISSUE THREAD

**Issue by XtremePlayzCODE** [daniktheboss/AlphaMc#1]
Invite me to the repo and I will help, maybe we should put this on an orginazation? Nvm, I will create the orginazation repo and I'll fork this repo so we can work there

**Comment by daniktheboss** [comment]
Ok, delete that repo I'll do one. Got a name in mind

**Comment by XtremePlayzCODE** [comment]
what?

**Comment by XtremePlayzCODE** [comment]
an organization?

**Comment by XtremePlayzCODE** [comment]
already made it, sry https://github.com/AlphaMCTeam/AlphaMC

**Comment by XtremePlayzCODE** [comment]
we can always rename the repo and org name

**Comment by daniktheboss** [comment]
I want to make my own cus owner of repo has more perms then others.

**Comment by XtremePlayzCODE** [comment]
ok i can transfer the repo to your own org

**Comment by XtremePlayzCODE** [comment]
and why do you want more perms lol

**Comment by XtremePlayzCODE** [comment]
you only get invite perms and admins dont so...

**Comment by daniktheboss** [comment]
Idk just lol

**Comment by XtremePlayzCODE** [comment]
well its yours so go ahead and make the org, ill transfer the repo

**Comment by XtremePlayzCODE** [comment]
i see you want to invite robske

**Comment by daniktheboss** [comment]
Yes cus he know how the server works

**Comment by XtremePlayzCODE** [comment]
did you make the org

**Comment by XtremePlayzCODE** [comment]
?

**Comment by XtremePlayzCODE** [comment]
Wait, i can transfer owner perms to you

**Comment by XtremePlayzCODE** [comment]
ok dont make an org, accept my invite ill give you owner

**Comment by XtremePlayzCODE** [comment]
go to [here](https://github.com/AlphaMCTeam)

**Comment by daniktheboss** [comment]
Lol already did the org

**Comment by XtremePlayzCODE** [comment]
lmaoooooooooooooooooooooooooooooooooooo

**Comment by XtremePlayzCODE** [comment]
fine ill transfer it

**Comment by daniktheboss** [comment]
Ok, save the readme and I'll add the repo to the org and you will commit

**Comment by XtremePlayzCODE** [comment]
whats the org name

**Comment by XtremePlayzCODE** [comment]
whats the org name

**Comment by XtremePlayzCODE** [comment]
??????

**Comment by XtremePlayzCODE** [comment]
whats the org name>?????

**Comment by daniktheboss** [comment]
Deleting this repo... comment on xpocket
